// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtczmajzzrgdcbcvikgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0Y3ptYWp6enJnZGNiY3Zpa2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyOTEwOTksImV4cCI6MjA3Nzg2NzA5OX0.BrarNcPSCKcbk8_wURr-1F2qH93d8wkz1zc3lLX0YsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});